language: node_js

before_install:
  - npm install -g grunt-cli
  - cd src

install: npm install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fdd9770e59a8aef8a04a
    on_success: change
    on_failure: always
    on_start: change
